--- #YAML:1.0
name: Graph-Usage
abstract: ~
version: 0.11
version_from: lib/Graph/Usage.pm
license: gpl
distribution_type: module
generated_by: Graph-Usage version 0.11
installdirs: site
requires:
  Graph::Easy: 0.36
  Heap: 0.71
  Scalar::Util: 1.13
